version: '2.3'

volumes:
  workspace:

services:

  master:
    image: ros:noetic-ros-core-focal
    container_name: ros_master
    init: true
    restart: unless-stopped
    command: roscore

  ros1_bridge:
    image: ros:foxy-ros1-bridge-focal
    container_name: ros1_bridge
    init: true
    restart: unless-stopped
    command: ros2 run ros1_bridge dynamic_bridge
    depends_on: 
      - master
    environment:
      - ROS_MASTER_URI=http://master:11311

  workspace:
    build: ./workspace
    image: wn1980/workspace${TAG}
    container_name: ros_workspace
    init: true
    restart: unless-stopped
    privileged: true
    depends_on: 
      - master
    environment:
      - DISPLAY=:1
      - ROS_MASTER_URI=http://master:11311
      #- QT_X11_NO_MITSHM=1
      #- TURTLEBOT_3D_SENSOR=asus_xtion_pro
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/run/systemd:/run/systemd"
      - "/etc/localtime:/etc/localtime:ro"
      - "workspace:/workspace"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1m"
      retries: 20
    ports:
      #- "11311:11311"
      - "8558:8558"
      - "9901:9901"

  joystick:
    build: ./joystick
    image: wn1980/joystick${TAG}
    container_name: ros_joystick
    init: true
    restart: unless-stopped
    privileged: true
    depends_on:
      - workspace
    devices:
      - "/dev/input:/dev/input"
    volumes:
      - "/dev/input:/dev/input"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - ROS_MASTER_URI=http://master:11311    

  ydlidar:
    build: ./ydlidar
    image: wn1980/ydlidar${TAG}
    container_name: ros_ydlidar
    init: true
    restart: unless-stopped
    privileged: true
    depends_on:
      - workspace
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - ROS_MASTER_URI=http://master:11311    

  ros2:
    build: ./ros2
    image: wn1980/ros2${TAG}
    container_name: ros2_workspace
    init: true
    restart: unless-stopped
    environment:
      - DISPLAY=:1
    privileged: true
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/run/systemd:/run/systemd"
      - "/etc/localtime:/etc/localtime:ro"
      - "workspace:/workspace"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1m"
      retries: 20
    ports:
      - "8559:8558"
      - "9902:9901"