version: '2.3'

volumes:
  workspace:

services:

  workspace:
    build: ./workspace
    image: wn1980/workspace${TAG}
    container_name: ros_workspace
    init: true
    restart: unless-stopped
    environment:
      - DISPLAY=:1
      #- QT_X11_NO_MITSHM=1
      #- ROS_MASTER_URI=http://localhost:11311
      #- TURTLEBOT_3D_SENSOR=asus_xtion_pro
    privileged: true
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/run/systemd:/run/systemd"
      - "/etc/localtime:/etc/localtime:ro"
      - "workspace:/workspace"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1m"
      retries: 20
    ports:
      #- "11311:11311"
      - "8558:8558"
      - "9901:9901"
