version: "2.3"

networks:
  default:
    external:
      name: ros-network

services:

  teleop-web:
    #build: ./image
    image: wn1980/teleop-web-ros${TAG}
    container_name: ros_teleop_web
    init: true
    restart: unless-stopped
    environment:
      - ROS_MASTER_URI=http://master:11311   
    ports:
      - "3003:8000"
