version: '2.3'

# create default network
networks:
  default:
    external:
      name: ros-network

services:

  webrtc:
    build: ./image
    image: wn1980/webrtc-ros${TAG}
    container_name: ros_webrtc
    init: true
    restart: unless-stopped
    privileged: true
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/etc/localtime:/etc/localtime:ro"
      - "./asoundrc.txt:/root/.asoundrc:rw"
    environment:
      - ROS_MASTER_URI=http://master:11311
    ports:
      - 8088:8080
