version: '2.3'

# create default network
networks:
  default:
    external:
      name: ros-network

services:

  web-app:
    build: ./image
    image: wn1980/web-app-ros${TAG}
    container_name: ros_web_app
    init: true
    restart: unless-stopped
    privileged: true
    #devices:
    #  - "/dev/input:/dev/input"
    volumes:
      #- "/dev/input:/dev/input"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - ROS_MASTER_URI=http://localhost:11311
    ports:
      - 80:7000 
