version: '2.3'

# create default network
#networks:
#  default:
#    external:
#      name: ros-network

volumes:
  workspace:

services:

  ros2:
    #build: ./image
    image: wn1980/ros2-foxy${TAG}
    container_name: ros2_foxy
    init: true
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/run/systemd:/run/systemd"
      - "/etc/localtime:/etc/localtime:ro"
      - "workspace:/workspace"
      - "~/.gitconfig:/home/developer/.gitconfig"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1m"
      retries: 20
    environment:
      - ROS_DOMAIN_ID=50
      - DISPLAY=:1
    #ports:
    #  - "8559:8008"
    #  - "9902:6901"

  master:
    image: ros:noetic-ros-core-focal
    container_name: ros1_master
    init: true
    restart: always
    network_mode: host
    command: roscore
  #  expose:
  #    - 11311
  #  ports:
  #    - "11311:11311"

  ros1_to_ros2:
    image: ros:foxy-ros1-bridge-focal
    container_name: ros1_to_ros2
    init: true
    restart: always
    network_mode: host
    command: ros2 run ros1_bridge dynamic_bridge --bridge-all-topics
    #depends_on: 
    #  - master
    environment:
      - ROS_DOMAIN_ID=50
      - ROS_MASTER_URI=http://localhost:11311
