version: '2.3'

# create default network
networks:
  default:
    external:
      name: ros-network

services:

  sensor3d:
    build: ./image
    image: wn1980/sensor3d-ros${TAG}
    container_name: ros_sensor3d
    init: true
    restart: unless-stopped
    privileged: true
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - ROS_MASTER_URI=http://master:11311
