version: '2.3'

# create default network
networks:
  default:
    external:
      name: ros-network

services:

  twist-mux:
    #build: ./image
    image: wn1980/twist-mux-ros${TAG}
    container_name: ros_twist_mux
    init: true
    restart: unless-stopped
    privileged: true
    #devices:
    #  - "/dev/input:/dev/input"
    volumes:
      #- "/dev/input:/dev/input"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - ROS_MASTER_URI=http://master:11311
    ports:
      - 7000:7000 
